[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=I
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
AdminQuietInstCmd=%AdminQuietInstCmd%
UserQuietInstCmd=%UserQuietInstCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=D:\Dropbox\AA -Ecriture\Atelier d'écrivain\atelier-supabase\atelier-ecrivain\cursus.exe
FriendlyName=Cursus
AppLaunched=Lancer Atelier.bat
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
FILE0="Lancer Atelier.bat"
[SourceFiles]
SourceFiles0=D:\Dropbox\AA -Ecriture\Atelier d'écrivain\atelier-supabase\atelier-ecrivain\
[SourceFiles0]
%FILE0%=
